"""create tool capability association

Revision ID: 0584dbe9d07e
Revises: 72894838eca1
Create Date: 2026-09-09 19:03:50.616301

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0584dbe9d07e"
down_revision: str | Sequence[str] | None = "72894838eca1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_capabilities",
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("capability_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"], ["capabilities.capability_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tool_id"], ["tools.tool_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tool_id", "capability_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_capabilities")
    # ### end Alembic commands ###
