"""create agent tool association

Revision ID: 72894838eca1
Revises: 29f338f792b7
Create Date: 2026-09-08 14:41:00.993159

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72894838eca1"
down_revision: str | Sequence[str] | None = "29f338f792b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tools",
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.agent_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_id"], ["tools.tool_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("agent_id", "tool_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_tools")
    # ### end Alembic commands ###
