"""add policy priority

Revision ID: 9632987c988f
Revises: ea59a4d90a5b
Create Date: 2026-09-16 19:59:57.267745

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9632987c988f"
down_revision: str | Sequence[str] | None = "ea59a4d90a5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "policies",
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("policies", "priority")
    # ### end Alembic commands ###
