"""create agent capability association

Revision ID: b5e5c113d4b3
Revises: fc97c2d4be70
Create Date: 2026-09-05 19:20:35.328489

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5e5c113d4b3"
down_revision: str | Sequence[str] | None = "fc97c2d4be70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_capabilities",
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column("capability_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.agent_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["capability_id"], ["capabilities.capability_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("agent_id", "capability_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_capabilities")
    # ### end Alembic commands ###
