"""add policy constraints

Revision ID: fa516fe95cfb
Revises: 42e716a81507
Create Date: 2026-09-11 19:59:36.039921

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa516fe95cfb"
down_revision: str | Sequence[str] | None = "42e716a81507"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_policies_decision",
        "policies",
        "decision IN ('ALLOW', 'DENY', 'REQUIRE_APPROVAL')",
    )
    op.create_check_constraint(
        "ck_policies_environment",
        "policies",
        "environment IN ('dev', 'test', 'qa', 'ppd', 'prod')",
    )
    op.create_check_constraint(
        "ck_policies_risk_level",
        "policies",
        "risk_level IN ('low', 'medium', 'high', 'critical')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_policies_risk_level", "policies", type_="check")
    op.drop_constraint("ck_policies_environment", "policies", type_="check")
    op.drop_constraint("ck_policies_decision", "policies", type_="check")
    # ### end Alembic commands ###
