"""create capabilities table

Revision ID: fc97c2d4be70
Revises: c190640013b3
Create Date: 2026-09-05 19:02:39.609534

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc97c2d4be70'
down_revision: str | Sequence[str] | None = 'c190640013b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capabilities', 'agent_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capabilities', sa.Column('agent_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
